### ISSUE TITLE
Relay Modern example

### ISSUE THREAD

**Issue by leebenson** [reactql/examples#1]
Show how Apollo could be swapped out for Relay, and what the potential pros/cons are.

Open to PRs!

**Comment by Extra-lightwill** [comment]
@leebenson see here for a basic example Relay Modern integration: https://github.com/Extra-lightwill/kit

**Comment by leebenson** [comment]
Thanks @Extra-lightwill. There's a thread at https://github.com/reactql/kit/issues/36 with an open show of hands for integrating first-class Relay Modern. I'm looking for a broader consensus of whether Relay is preferred over Apollo, and the reasons why.

If you want to add some thoughts to that thread, please do!

**Comment by leebenson** [comment]
Given the awesome work Apollo is doing, the imminent Apollo Client 2.0 release and how deeply Apollo is now embedded in the stack (both server and client), I think it's unlikely that a move to Relay Modern will get 'official' support from ReactQL core anytime soon, so I'll close this for now.
