### ISSUE TITLE
Organization: Branch Per Example?

### ISSUE THREAD

**Issue by tim-soft** [reactql/examples#10]
I think organizationally speaking, it would make a lot more sense to have a separate branch per example versus throwing the kitchen sink into one, then cloning wouldn't be as messy.

I wouldn't mind contributing to a subscriptions/graphql-tools branch

**Comment by leebenson** [comment]
I agree that things can be improved. I think even a separate repo per project. Clean and easy. Will get this re-jigged.

**Comment by leebenson** [comment]
And thanks for your suggestion of taking care of a subscriptions example, @tim-soft. If you have a preferred name for that, let me know, and I'll create a new project and assign you to it.

I'll add projects under a `reactql/example-` prefix.

**Comment by tim-soft** [comment]
reactql/example-subscriptions would seem appropriate on the surface, although I'm still wondering how to best distribute the code. 

Subscriptions in general should probably be an opt-in feature given the current state of GraphQL and the websocket server requirement, but how closely should their integration be to the kit repo? Some of the integration could bleed into the kit files -- maybe this problem is best solved in the kit repo as a 'subscriptions' branch?

If someone wanted subscriptions _and_ the auth example, you could download the kit with stubs for a ws server. I definitely would like to contribute to the project either way. What do you think?

**Comment by leebenson** [comment]
I'll have a think about this some more. It would be good to have some 'official' hooks for subscriptions without having to edit the kit. I'd like to avoid needing to delve under the hood too much, or splintering the project into multiple versions that need maintaining.
