### ISSUE TITLE
I'm not sure how to ask a general question on github, but how can I get a mutation that has 4 fields with this style of gql server?

### ISSUE THREAD

**Issue by birdiesanders** [reactql/examples#4]
I'm not familiar with Koa like I am express, but I do love how you have this implemented. I'm running into a point where I just can't figure out how to implement a mutation in this style though.

I need this:

A mutation that makes an object with 5 elements; "target", "alertType", "count", "lightNeeded", and "lightAction".

I am pretty much trying to get 5 pieces of data from the client back to the server, and delivered to a single function via the object from the mutation. 

Any docs for this kind of gql implementation?

**Comment by leebenson** [comment]
Check out http://dev.apollodata.com/react/mutations.html

The `/graphql` endpoint that is set-up in the [GraphQL server example](https://github.com/reactql/examples/blob/master/graphql-server/kit/entry/server.js#L192-L196) accepts POST, which all GraphQL queries (and mutations) are sent as. So it's already 'compatible' with mutations.

You can then implement your mutation schema in [kit/lib/schema.js](https://github.com/reactql/examples/blob/master/graphql-server/kit/lib/schema.js), so your server is ready to accept mutations.

Finally, you can test your queries/mutations by navigating to `/graphql` on your server in the browser -- which uses [GraphiQL](https://github.com/graphql/graphiql) to run/debug queries.

**Comment by birdiesanders** [comment]
I get that, I just don't know how to implement mutations in the *style* you have this set up, but I like the way queries are built, and want to learn how to build the mutation in that way.

**Comment by birdiesanders** [comment]
This is how I started going about this, but it keeps yelling at me that the Mutation type must be of the Output Type.

```
const Mutation = new GraphQLObjectType({
  name: 'Mutation',
  description: 'Issue an alert',
  fields() {
    return {
      Alert: {
        type: 'Output',
        resolve() {
          return getSystemInfo()
        }
      }
    }
  }
});
```

**Comment by leebenson** [comment]
Your schema isn't valid.

Watch my YouTube vid: https://www.youtube.com/watch?v=DNPVqK_woRQ

[36:52](https://youtu.be/DNPVqK_woRQ?t=36m52s) specifically deals with mutations, and how to write the schema for a mutation.

**Comment by birdiesanders** [comment]
Oh wow, that one segment of video enlightened me. I was not expecting that to smash together all the graphql/react information I have been researching, but 3 minutes later, I have 90% of what I have been working towards. I will be watching every video you have on youtube...

**Comment by leebenson** [comment]
Glad it helped @birdiesanders 👍
