### ISSUE TITLE
Apollo Client does not use the pollingInterval option.

### ISSUE THREAD

**Issue by birdiesanders** [reactql/examples#5]
I have tried to set Apollo to use a pollingInterval to update, but I cannot seem to get it to function. How should I go about this?

**Comment by leebenson** [comment]
Did you follow this? http://dev.apollodata.com/react/receiving-updates.html#polling

**Comment by birdiesanders** [comment]
I figured it out, I'm not used to decorators. 

Now that I have that figured out, could you possibly help me figure out when I keep getting errors in decorated components? As far as I can tell, it's trying to render before the props have been filled.

**Comment by leebenson** [comment]
Please post to [stackoverflow](http://stackoverflow.com/), using the `reactql` tag if it's something specific to this starter kit.
