### ISSUE TITLE
ReactQL with CSSinJS?

### ISSUE THREAD

**Issue by TLevesque** [reactql/examples#8]
ReactQL looks to be an awesome framework, I have a just a question about it: Can ReactQL work with CSSinJS libraries like Aphrodite or Styled-Components? If it the case, is there some examples out there? Thanks for your help!

**Comment by gihrig** [comment]
I use ReactQL with styled-components - no problem. 

Just follow the styled-components [instructions](https://www.styled-components.com/docs/basics#installation).

This really has nothing to do with ReactQL. You can use css and css-in-js solutions as you want without further support from ReactQL. Just try it ;-)

**Comment by leebenson** [comment]
What @gihrig said.

If you run into any specific errors, please post code and I'd happily take a look. I'll close this in the meantime.

**Comment by TLevesque** [comment]
That's great to be able to use styled-components! Thank you very much!
